format = """
[](black)\
$os\
$username\
[](fg:black bg:red)\
$directory\
[](fg:red bg:orange)\
$git_branch\
$git_status\
[](fg:orange bg:peach)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:peach bg:orange_light)\
$kubernetes\
$docker_context\
[](fg:orange_light bg:black)\
$time\
[ ](fg:black)\
$line_break$character"""

palette = "nvimgelion"

[palettes.nvimgelion]
text1 = "#984695"
text = "#734f9a"
black = "#281d2d"
red = "#ed2323"
orange = "#ea8533"
peach = "#fbe6e5"
orange_light = "#f99d52"
green = "#8bd450"

[os]
disabled = false
style = "bg:black fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:black fg:text"
style_root = "bg:black fg:text"
format = '[ $user ]($style)'

[directory]
style = "bg:red fg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"
read_only = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:orange"
format = '[[ $symbol $branch ](fg:text bg:orange)]($style)'

[git_status]
style = "bg:orange"
format = '[[($all_status$ahead_behind )](fg:text bg:orange)]($style)'

[nodejs]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[c]
symbol = " "
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[dotnet]
symbol = " "
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[rust]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[golang]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[php]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[java]
symbol = " "
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[kotlin]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[haskell]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[python]
symbol = ""
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[lua]
symbol = " "
style = "bg:peach"
format = '[[ $symbol( $version) ](fg:text bg:peach)]($style)'

[kubernetes]
disabled = true
symbol = "󱃾"
style = "bg:orange_light"
format = '[[ $symbol ctx:( $context) n:( $namespace)](fg:text bg:orange_light)]($style)'

[docker_context]
symbol = ""
style = "bg:orange_light"
format = '[[ $symbol( $context) ](fg:text bg:orange_light)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:black"
format = '[[  $time ](fg:text bg:black)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
